### ISSUE TITLE
the link for linemod doesn't work

### ISSUE THREAD

**Issue by monajalal** [sailor-z/Unseen_Object_Pose#3]
Hi,

The link you have provided for linemod  doesn't work. 
Can you  please provide another link?
I see the following on BOP challenge but I am not sure where to download the `linemod_zhs` ?
```
export SRC=https://bop.felk.cvut.cz/media/data/bop_datasets
wget $SRC/lm_base.zip         # Base archive with dataset info, camera parameters, etc.
wget $SRC/lm_models.zip       # 3D object models.
wget $SRC/lm_test_all.zip     # All test images ("_bop19" for a subset used in the BOP Challenge 2019/2020).
wget $SRC/lm_train_pbr.zip    # PBR training images (rendered with BlenderProc4BOP).

unzip lm_base.zip             # Contains folder "lm".
unzip lm_models.zip -d lm     # Unpacks to "lm".
unzip lm_test_all.zip -d lm   # Unpacks to "lm".
unzip lm_train_pbr.zip -d lm  # Unpacks to "lm".
```

**Comment by sailor-z** [comment]
Hi,
This link works for me: https://e1.pcloud.link/publink/show?code=XZqxumZkU8RqFs7NNuAvSovrRGgtLvR39ry

**Comment by monajalal** [comment]
![Screenshot from 2023-02-16 16-44-06](https://user-images.githubusercontent.com/1892917/219493866-77eef729-6f34-4f04-81dc-a8f4028e2ae1.png)



When I click on "ignore the risk" it tells the link is not valid.

![Screenshot from 2023-02-16 16-44-16](https://user-images.githubusercontent.com/1892917/219493913-26623e51-7ee2-4faf-a247-397fb5abd96b.png)


Would you please be able to upload it elsewhere like OneDrive or GoogleDrive?

**Comment by sailor-z** [comment]
The link works fine for me. I'm using Google Chrome. I'll try to upload it to GoogleDrive. 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/26895204/219936008-ba2dff98-0ef4-4c6f-95f2-ab19931613a3.png">
