### ISSUE TITLE
will this work on novel objects that also have novel class names that not necessarily have a lot of visual similarity with objects/classes in the training?

### ISSUE THREAD

**Issue by monajalal** [sailor-z/Unseen_Object_Pose#4]

**Comment by sailor-z** [comment]
I'm sorry I don't really understand. Could you please explain more about the question?

**Comment by monajalal** [comment]
Thanks a lot for your response.

Imagine that we have only dogs, cats, and dolphins in our training dataset. Would this be able to do inference on ducks if I provide the RGB photo of the duck as well as the 3D mesh of the duck during inference time?

**Comment by sailor-z** [comment]
Sure. That's our point. Our method can handle the unseen object (ducks in your case) pose estimation without retraining.
