### ISSUE TITLE
Example/Tutorial for getting inference on my own custom unknown object

### ISSUE THREAD

**Issue by monajalal** [sailor-z/Unseen_Object_Pose#7]
Thanks a lot for your great repo. Could you please provide instructions how we can get inference on our own custom unknown unseen object?

**Comment by sailor-z** [comment]
To test our method on the custom unseen objects, you need to first get a set of reference images with known object poses by rendering the 3d object model. An alternative strategy is taking some pictures of the object from different viewpoints and then calibrating the camera poses by using visualSFM or COLMAP. Once you get these reference images, you can run our method to get the 3d orientation of an object in the source image.
