### ISSUE TITLE
A problem about your cost function

### ISSUE THREAD

**Issue by pyni** [sailor-z/Unseen_Object_Pose#8]
Hi, Thanks for sharing the code. I have a question about the weighted infoNCE loss in your paper(equation 6). 
It seems that the numerator should not have weight (wij)  because it needs to minimize the loss of the numerator. 
The equation  (5) in paper https://arxiv.org/pdf/2105.05643.pdf shares the same idea. It also has no weight for the numerator.

**Comment by sailor-z** [comment]
Hi,

Thanks for the question and sorry for the late reply. We found that the loss function in the PoseContrast paper does not work in some cases. The range of the weight is from 0 to 1. If I only weight the denominator, the sum might be smaller than the numerator.

**Comment by pyni** [comment]
OK, Thanks for your reply.
